# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circle_annotation_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.messages.color_msg as color__msg__pb2
import src.messages.point2_msg as point2__msg__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ircle_annotation_msg.proto\x12\x08\x66oxglove\x1a\x0f\x63olor_msg.proto\x1a\x10point2_msg.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n\x10\x43ircleAnnotation\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x08position\x18\x02 \x01(\x0b\x32\x10.foxglove.Point2\x12\x10\n\x08\x64iameter\x18\x03 \x01(\x01\x12\x11\n\tthickness\x18\x04 \x01(\x01\x12#\n\nfill_color\x18\x05 \x01(\x0b\x32\x0f.foxglove.Color\x12&\n\routline_color\x18\x06 \x01(\x0b\x32\x0f.foxglove.Colorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'circle_annotation_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CIRCLEANNOTATION._serialized_start=110
  _CIRCLEANNOTATION._serialized_end=325
# @@protoc_insertion_point(module_scope)
