# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: img_annotation_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.messages.circle_annotation_msg as circle__annotation__msg__pb2
import src.messages.points_annotation_msg as points__annotation__msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18img_annotation_msg.proto\x12\x08\x66oxglove\x1a\x1b\x63ircle_annotation_msg.proto\x1a\x1bpoints_annotation_msg.proto\"k\n\x10ImageAnnotations\x12+\n\x07\x63ircles\x18\x01 \x03(\x0b\x32\x1a.foxglove.CircleAnnotation\x12*\n\x06points\x18\x02 \x03(\x0b\x32\x1a.foxglove.PointsAnnotationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'img_annotation_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEANNOTATIONS._serialized_start=96
  _IMAGEANNOTATIONS._serialized_end=203
# @@protoc_insertion_point(module_scope)
