# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rimu_msg.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n\nIMUMessage\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x02 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x03 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x04 \x01(\x02\x12\x10\n\x08orient_w\x18\x05 \x01(\x02\x12\x10\n\x08orient_i\x18\x06 \x01(\x02\x12\x10\n\x08orient_j\x18\x07 \x01(\x02\x12\x10\n\x08orient_k\x18\x08 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMUMESSAGE._serialized_start=51
  _IMUMESSAGE._serialized_end=233
# @@protoc_insertion_point(module_scope)
